services:
  - type: web
    name: n8n-service
    plan: free
    envVars:
      - key: N8N_ENCRYPTION_KEY
        generateValue: true
      - key: WEBHOOK_URL
        value: https://n8n-service.onrender.com/
      - key: N8N_WEBHOOK_TUNNEL_URL
        value: https://n8n-service.onrender.com/
    disk:
      name: n8n-data
      mountPath: /home/node/.n8n
      sizeGB: 1
    runtime: docker
