services:
  - type: web
    plan: free
    name: n8n-service
    envVars:
      - key: N8N_ENCRYPTION_KEY
        generateValue: true
    buildCommand: docker build -t n8n-custom .
    startCommand: docker run -p 10000:5678 n8n-custom
