services:
  - type: web
    name: n8n-service
    plan: free
    runtime: docker
    envVars:
      - key: N8N_ENCRYPTION_KEY
        generateValue: true
      - key: WEBHOOK_URL
        value: https://n8n-service.onrender.com/
      - key: N8N_WEBHOOK_TUNNEL_URL
        value: https://n8n-service.onrender.com/
